@startuml
' node node_modules/pegjs/bin/pegjs src/plantuml.pegjs src/plantuml.js
' node plantcode -l coffeescript tests/complex/classnames.plantuml > tests/complex/classnames.coffee

class someclass {
}

class §$noQuotes|_:;~#!§$()[]+-*\/,| {
}

class "inQuotes" {
}

class "AZaz09 |_:;~#!§$()[]+-*\/,{}|" {
}

@enduml