
const fs = require("fs");
const index = require("../src/plantcode");

const supportedLanguages = index.getSupportedLanguages();

let output = "// DO NOT EDIT THIS FILE. GENERATED WITH scripts/build_templates.js\n";

supportedLanguages.forEach(function (supportedLanguage) {
  let template = fs.readFileSync("./templates/" + supportedLanguage + ".hbs").toString();
  template = template.replace(/\$/g, "\\$$");
  output += `exports.${supportedLanguage} = \`${template}\`;\n`;
});

fs.writeFileSync('./templates/index.js', output);
